application:
  port: 8000
  hmac_secret: "super-long-and-secret-random-key-needed-to-verify-message-integrity"
redis_uri: "redis://127.0.0.1:6379"
database:
  username: "postgres"
  password: "123123"
  host: "127.0.0.1"
  port: 5432
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@zero2prod.com"
  authorization_token: ""
  timeout_milliseconds: 10000
