application:
  port: 8000
database:
  username: "postgres"
  password: "123123"
  host: "127.0.0.1"
  port: 5432
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@zero2prod.com"
  authorization_token: ""
  timeout_milliseconds: 10000
