name: Security audit

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@cargo-deny
      - name: Install cargo-audit
        run: cargo install --force --locked cargo-audit
      - name: Scan for vulnerabilities with cargo deny
        run: cargo deny check advisories
      - name: Scan for vulnerabilities with cargo audit
        run: cargo audit
