name: Security audit

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install the Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install cargo-deny and cargo-audit
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny,cargo-audit
      - name: Scan for vulnerabilities with cargo deny
        run: cargo deny check advisories
      - name: Scan for vulnerabilities with cargo audit
        run: cargo audit
